_format_version: "3.0"
_transform: true

services:
  - name: rest
    url: http://rest:3000/
    routes:
      - name: rest-all
        paths: [/rest/v1/]
        strip_path: true
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: [GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD]
          headers:
            [
              Accept,
              Accept-Language,
              Authorization,
              Content-Type,
              apikey,
              x-client-info,
              x-supabase-api-version,
              x-retry-count,
              accept-profile,
              content-profile,
              prefer,
              range,
            ]
          exposed_headers: [Content-Range, Content-Location]
          credentials: true

  - name: auth
    url: http://auth:9999/
    routes:
      - name: auth-all
        paths: [/auth/v1/]
        strip_path: true
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: [GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD]
          headers:
            [
              Accept,
              Accept-Language,
              Authorization,
              Content-Type,
              apikey,
              x-client-info,
              x-supabase-api-version,
              x-retry-count,
            ]
          exposed_headers: [Content-Range, Content-Location]
          credentials: true
