-- License analysis tables
CREATE TABLE IF NOT EXISTS public.user_licenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_db text NOT NULL,
  user_code text NOT NULL,
  user_name text NOT NULL,
  is_locked boolean NOT NULL DEFAULT false,
  has_license boolean NOT NULL DEFAULT false,
  license_type text CHECK (license_type IN ('PRO','CRM') OR license_type IS NULL),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_db, user_code)
);

ALTER TABLE public.user_licenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage user_licenses" ON public.user_licenses
  FOR ALL TO authenticated USING (has_role(auth.uid(),'admin'::app_role)) WITH CHECK (has_role(auth.uid(),'admin'::app_role));
CREATE POLICY "Authenticated read user_licenses" ON public.user_licenses
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated update user_licenses" ON public.user_licenses
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER trg_user_licenses_updated_at BEFORE UPDATE ON public.user_licenses
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_user_licenses_company ON public.user_licenses(company_db);

CREATE TABLE IF NOT EXISTS public.license_pricing (
  license_type text PRIMARY KEY CHECK (license_type IN ('PRO','CRM')),
  monthly_cost numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'BRL',
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.license_pricing ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage license_pricing" ON public.license_pricing
  FOR ALL TO authenticated USING (has_role(auth.uid(),'admin'::app_role)) WITH CHECK (has_role(auth.uid(),'admin'::app_role));
CREATE POLICY "Authenticated read license_pricing" ON public.license_pricing
  FOR SELECT TO authenticated USING (true);

INSERT INTO public.license_pricing (license_type, monthly_cost) VALUES ('PRO', 1300), ('CRM', 900)
  ON CONFLICT (license_type) DO NOTHING;

INSERT INTO public.user_licenses (company_db, user_code, user_name, is_locked, has_license, license_type) VALUES
('SBO_INSTITUTO_ANA','AlertSvc','AlertSvc',false,false,NULL),
('SBO_INSTITUTO_ANA','Apiuser','Apiuser',false,false,NULL),
('SBO_INSTITUTO_ANA','Ludmila.braga','Ludmila Braga',false,false,NULL),
('SBO_INSTITUTO_ANA','Support','Support',false,false,NULL),
('SBO_INSTITUTO_ANA','alef.alves','Alef Alves',true,false,NULL),
('SBO_INSTITUTO_ANA','alexandra.monteiro','Alexandra Monteiro',false,true,'PRO'),
('SBO_INSTITUTO_ANA','ana.fernandes','Ana Fernandes',false,true,'PRO'),
('SBO_INSTITUTO_ANA','anderson.araujo','Anderson Araujo',false,true,'PRO'),
('SBO_INSTITUTO_ANA','andre.andrade','Andre Andrade',false,true,'PRO'),
('SBO_INSTITUTO_ANA','andre.souza','Andre Souza',false,true,'PRO'),
('SBO_INSTITUTO_ANA','andre.viana','Andre Viana',false,false,NULL),
('SBO_INSTITUTO_ANA','artur.angelo','Artur Angelo',false,true,'PRO'),
('SBO_INSTITUTO_ANA','augusto.nascimento','Augusto Nascimento',false,true,'PRO'),
('SBO_INSTITUTO_ANA','barbara.maciel','Barbara Maciel',false,true,'PRO'),
('SBO_INSTITUTO_ANA','blenda.pinheiro.ext','Blenda Pinheiro',false,true,'PRO'),
('SBO_INSTITUTO_ANA','bruno.diego','Bruno Diego',false,false,NULL),
('SBO_INSTITUTO_ANA','cesar.silva','Cesar Silva',false,true,'PRO'),
('SBO_INSTITUTO_ANA','cibele.costa','Cibele Costa',false,false,NULL),
('SBO_INSTITUTO_ANA','daniela.camargos','Daniela Camargos',false,true,'PRO'),
('SBO_INSTITUTO_ANA','diogo.faria','Diogo Faria',false,true,'PRO'),
('SBO_INSTITUTO_ANA','douglas.vinicius','Douglas Vinicius',false,false,NULL),
('SBO_INSTITUTO_ANA','elisia.oliveira','Elisia Oliveira',false,false,NULL),
('SBO_INSTITUTO_ANA','felipe.escudeiro','Felipe Escudeiro',false,true,'PRO'),
('SBO_INSTITUTO_ANA','fernanda.faria','Fernanda Faria',false,true,'PRO'),
('SBO_INSTITUTO_ANA','fernanda.lobato','Fernanda Lobato',false,true,'PRO'),
('SBO_INSTITUTO_ANA','fernando.honorato','Fernando Honorato',false,false,NULL),
('SBO_INSTITUTO_ANA','flavia.alves','Flavia Alves',false,true,'PRO'),
('SBO_INSTITUTO_ANA','gabriel.barbosa','Gabriel Barbosa',false,false,NULL),
('SBO_INSTITUTO_ANA','gabriela.moura','Gabriela Moura',false,true,'PRO'),
('SBO_INSTITUTO_ANA','graciela.fernandes','Graciela Fernandes',false,true,'PRO'),
('SBO_INSTITUTO_ANA','gustavo.freitas','Gustavo Freitas',false,true,'PRO'),
('SBO_INSTITUTO_ANA','isabelle.santos','Isabelle Santos',false,true,'PRO'),
('SBO_INSTITUTO_ANA','izabella.cristina','Izabella Cristina',false,true,'PRO'),
('SBO_INSTITUTO_ANA','janaina.bezerra','Janaina Bezerra',false,false,NULL),
('SBO_INSTITUTO_ANA','jean.gomes','Jean Gomes',false,true,'PRO'),
('SBO_INSTITUTO_ANA','jose.victor','Jose Victor',false,true,'PRO'),
('SBO_INSTITUTO_ANA','juliana.gavineli','Juliana Gavineli',false,true,'PRO'),
('SBO_INSTITUTO_ANA','juliana.pinto','Juliana Pinto',false,false,NULL),
('SBO_INSTITUTO_ANA','juliana.rosa','Juliana Bernardin Rosa',false,true,'PRO'),
('SBO_INSTITUTO_ANA','ketlhenn.monteiro','Ketlhenn Monteiro',false,true,'PRO'),
('SBO_INSTITUTO_ANA','laryssa.mendes','Laryssa Mendes',false,true,'PRO'),
('SBO_INSTITUTO_ANA','leonardo.clemente','Leonardo Clemente',false,true,'PRO'),
('SBO_INSTITUTO_ANA','leonardo.oliveira','Leonardo Oliveira',false,true,'PRO'),
('SBO_INSTITUTO_ANA','leonardo.ramos','Leonardo Ramos',false,true,'PRO'),
('SBO_INSTITUTO_ANA','lucas.brandao','Lucas Brandao',false,true,'PRO'),
('SBO_INSTITUTO_ANA','lucas.carvalho','Lucas Carvalho',false,true,'PRO'),
('SBO_INSTITUTO_ANA','lucas.silva','Lucas Silva',false,true,'PRO'),
('SBO_INSTITUTO_ANA','luciana.marques','Luciana Marques',false,false,NULL),
('SBO_INSTITUTO_ANA','manager','Manager FGR Consultoria',false,true,'PRO'),
('SBO_INSTITUTO_ANA','marco.ferreira','Marco Ferreira',false,true,'PRO'),
('SBO_INSTITUTO_ANA','marco.tulio','Marco Tulio',true,true,'PRO'),
('SBO_INSTITUTO_ANA','marlon.pereira','Marlon Pereira',false,false,NULL),
('SBO_INSTITUTO_ANA','matheus.moreira','Matheus Moreira',false,true,'PRO'),
('SBO_INSTITUTO_ANA','matheus.viana','Matheus Viana',false,true,'PRO'),
('SBO_INSTITUTO_ANA','mauricio.farias','Mauricio Farias',false,true,'PRO'),
('SBO_INSTITUTO_ANA','natalia.costa','Natalia Costa',false,true,'PRO'),
('SBO_INSTITUTO_ANA','natan.santiago','Natan Santiago',false,true,'PRO'),
('SBO_INSTITUTO_ANA','roberto.giuliani','Roberto Giuliani',false,false,NULL),
('SBO_INSTITUTO_ANA','ronaldo.silva','Ronaldo Silva',false,true,'PRO'),
('SBO_INSTITUTO_ANA','samara.souza','Samara Souza',false,true,'PRO'),
('SBO_INSTITUTO_ANA','suporte','suporte FGR',false,false,NULL),
('SBO_INSTITUTO_ANA','tagiane.gomide','Tagiane Gomide',false,true,'PRO'),
('SBO_INSTITUTO_ANA','talita.lacerda','Talita Lacerda',false,true,'PRO'),
('SBO_INSTITUTO_ANA','tamara.barboza','Tamara Barboza',false,true,'PRO'),
('SBO_INSTITUTO_ANA','tarcisio.ferreira','Tarcisio Ferreira',false,true,'PRO'),
('SBO_INSTITUTO_ANA','tatieli.murta','Tatieli Murta',false,true,'PRO'),
('SBO_INSTITUTO_ANA','thadeu.botelho','Thadeu Botelho',false,true,'PRO'),
('SBO_INSTITUTO_ANA','thalitta.corona','Thaliatta Corona',false,true,'PRO'),
('SBO_INSTITUTO_ANA','thiago.moreira','Thiago Moreira',false,true,'PRO'),
('SBO_INSTITUTO_ANA','thiago.sousa','Thiago Sousa',false,false,NULL),
('SBO_INSTITUTO_ANA','valdineia.almeida','Valdineia Almeida',false,true,'PRO'),
('SBO_INSTITUTO_ANA','victor.mello','Victor Mello',false,false,NULL),
('SBO_INSTITUTO_ANA','vinicius.ribeiro','Vinicius Ribeiro',false,true,'PRO'),
('SBO_INSTITUTO_ANA','vitor.fernandes','Vitor Fernandes',false,true,'PRO'),
('SBO_INSTITUTO_ANA','vitoria.evelyn','Vitoria Evelyn',false,true,'PRO'),
('SBO_INSTITUTO_ANA','wellington.vieira','Wellingthon Vieira',false,true,'PRO'),
('SBO_ANAGAMING','AlertSvc','AlertSvc',false,false,NULL),
('SBO_ANAGAMING','Apiuser','USER API',false,false,NULL),
('SBO_ANAGAMING','Ludmila.braga','Ludmila Braga',true,false,NULL),
('SBO_ANAGAMING','Support','Support',false,false,NULL),
('SBO_ANAGAMING','alef.alves','Alef Alves',true,false,NULL),
('SBO_ANAGAMING','aline.alves','Aline Alves',true,false,NULL),
('SBO_ANAGAMING','ana.araujo','Ana Araujo',true,false,NULL),
('SBO_ANAGAMING','ana.fernandes','Ana Fernandes',false,true,'PRO'),
('SBO_ANAGAMING','anderson.araujo','Anderson Araujo',false,true,'PRO'),
('SBO_ANAGAMING','andre.andrade','Andre Andrade',false,true,'PRO'),
('SBO_ANAGAMING','andre.souza','Andre Souza',false,true,'PRO'),
('SBO_ANAGAMING','andre.viana','Andre Viana',true,false,NULL),
('SBO_ANAGAMING','antonio.guerardi','Antonio Guerardi',false,false,NULL),
('SBO_ANAGAMING','api_anaoffice','API ANA Office',false,false,NULL),
('SBO_ANAGAMING','api_anaops','API ANA OPS',true,false,NULL),
('SBO_ANAGAMING','api_automacao','api_automacao',false,false,NULL),
('SBO_ANAGAMING','artur.angelo','Artur Angelo',false,true,'PRO'),
('SBO_ANAGAMING','augusto.nascimento','Augusto Nascimento',false,true,'PRO'),
('SBO_ANAGAMING','barbara.maciel','Barbara Maciel',false,true,'PRO'),
('SBO_ANAGAMING','blenda.pinheiro.ext','Blenda Pinheiro',false,true,'PRO'),
('SBO_ANAGAMING','bruno.diego','Bruno Diego',true,false,NULL),
('SBO_ANAGAMING','bruno.rosa','Bruno Rosa',true,false,NULL),
('SBO_ANAGAMING','caio.ruiz','Caio Ruiz',true,false,NULL),
('SBO_ANAGAMING','camila.alcantara','Camila Alcantara',false,true,'PRO'),
('SBO_ANAGAMING','cesar.silva','Cesar Silva',false,true,'PRO'),
('SBO_ANAGAMING','cibele.costa','Cibele Costa',true,false,NULL),
('SBO_ANAGAMING','daniel.severino','Daniel Severino',false,true,'PRO'),
('SBO_ANAGAMING','daniela.camargos','Daniela Camargos',false,true,'PRO'),
('SBO_ANAGAMING','diego.fernandes','Diego Fernandes',true,false,NULL),
('SBO_ANAGAMING','diogo.faria','Diogo Faria',false,true,'PRO'),
('SBO_ANAGAMING','douglas.ferreira','Douglas Ferreira',false,true,'PRO'),
('SBO_ANAGAMING','douglas.vinicius','Douglas Vinicius',false,false,NULL),
('SBO_ANAGAMING','elisia.oliveira','Elisia Oliveira',false,false,NULL),
('SBO_ANAGAMING','felipe.coelho','Felipe Coelho',true,true,'PRO'),
('SBO_ANAGAMING','felipe.escudeiro','Felipe Escudeiro',false,true,'PRO'),
('SBO_ANAGAMING','fernanda.faria','Fernanda Faria',false,true,'PRO'),
('SBO_ANAGAMING','fernanda.lobato','Fernanda Lobato',false,true,'PRO'),
('SBO_ANAGAMING','fernanda.silva','Fernanda Silva',true,false,NULL),
('SBO_ANAGAMING','fernando.honorato','Fernando Honorato',true,false,NULL),
('SBO_ANAGAMING','filipe.molon','Filipe Molon',true,false,NULL),
('SBO_ANAGAMING','flavia.alves','Flavia Alves',false,true,'PRO'),
('SBO_ANAGAMING','flavio.farah.axm','Flavio Farah AXM',true,false,NULL),
('SBO_ANAGAMING','francielle.souza.ext','Francielle Souza',true,false,NULL),
('SBO_ANAGAMING','gabriel.barbosa','Gabriel Barbosa',true,false,NULL),
('SBO_ANAGAMING','gabriela.moura','Gabriela Moura',false,true,'PRO'),
('SBO_ANAGAMING','graciela.fernandes','Graciela Fernandes',false,true,'PRO'),
('SBO_ANAGAMING','gracielle.nascimento','Gracielle Nascimento',true,false,NULL),
('SBO_ANAGAMING','guilherme.gibran','Guilherme Gibran',true,false,NULL),
('SBO_ANAGAMING','gustavo.freitas','Gustavo Freitas',false,true,'PRO'),
('SBO_ANAGAMING','isabelle.santos','Isabelle Santos',false,true,'PRO'),
('SBO_ANAGAMING','isadora.crude','Isadora Crude',true,false,NULL),
('SBO_ANAGAMING','izabella.cristina','Izabella Cristina',false,true,'PRO'),
('SBO_ANAGAMING','janaina.bezerra','Janaina Bezerra',false,false,NULL),
('SBO_ANAGAMING','jean.gomes','Jean Gomes',false,true,'PRO'),
('SBO_ANAGAMING','jefferson.soares','Jefferson Soares',true,false,NULL),
('SBO_ANAGAMING','jose.couto','Jose Couto',true,false,NULL),
('SBO_ANAGAMING','jose.victor','Jose Victor',false,true,'PRO'),
('SBO_ANAGAMING','jucielle.quiterio','Julielle Quiterio',true,false,NULL),
('SBO_ANAGAMING','juliana.gavineli','Juliana Gavineli',false,true,'PRO'),
('SBO_ANAGAMING','juliana.monteiro','Juliana Monteiro',false,true,'PRO'),
('SBO_ANAGAMING','juliana.pinto','Juliana Pinto',false,false,NULL),
('SBO_ANAGAMING','juliana.rosa','Juliana Bernardin Rosa',false,true,'PRO'),
('SBO_ANAGAMING','ketlhenn.monteiro','Ketlhenn Monteiro',false,true,'PRO'),
('SBO_ANAGAMING','larissa.manzalli','Larissa Manzalli',false,true,'PRO'),
('SBO_ANAGAMING','laryssa.mendes','Laryssa Mendes',false,true,'PRO'),
('SBO_ANAGAMING','leonardo.clemente','Leonardo Clemente',false,true,'PRO'),
('SBO_ANAGAMING','leonardo.oliveira','Leonardo Oliveira',false,true,'PRO'),
('SBO_ANAGAMING','leonardo.ramos','Leonardo Ramos',false,true,'PRO'),
('SBO_ANAGAMING','leticia.silva','Leticia Silva',true,false,NULL),
('SBO_ANAGAMING','lincoln.vaz','Lincoln Vaz',false,true,'PRO'),
('SBO_ANAGAMING','lucas.brandao','Lucas Brandao',false,true,'PRO'),
('SBO_ANAGAMING','lucas.carvalho','Lucas Carvalho',false,true,'PRO'),
('SBO_ANAGAMING','lucas.ferraz','Lucas Ferraz',false,true,'PRO'),
('SBO_ANAGAMING','lucas.silva','Lucas Silva',false,true,'PRO'),
('SBO_ANAGAMING','luciana.marques','Luciana Marques',true,false,NULL),
('SBO_ANAGAMING','luiza.duarte','Luiza Duarte',false,true,'PRO'),
('SBO_ANAGAMING','maicon.vieira.axm','Maicon Vieira AXM',true,false,NULL),
('SBO_ANAGAMING','manager','Manager FGR Consultoria',false,true,'PRO'),
('SBO_ANAGAMING','marco.ferreira','Marco Ferreira',false,true,'PRO'),
('SBO_ANAGAMING','marco.tulio','Marco Tulio',false,true,'PRO'),
('SBO_ANAGAMING','marllon.angelis','Marllon Angelis',false,true,'PRO'),
('SBO_ANAGAMING','marlon.pereira','Marlon Pereira',true,false,NULL),
('SBO_ANAGAMING','marri.silva.axm','Marri Silva AXM',true,false,NULL),
('SBO_ANAGAMING','matheus.moreira','Matheus Moreira',false,true,'PRO'),
('SBO_ANAGAMING','matheus.viana','Matheus Viana',false,true,'PRO'),
('SBO_ANAGAMING','mauricio.farias','Mauricio Farias',false,true,'PRO'),
('SBO_ANAGAMING','miguel.valadares','Miguel Valadares',false,true,'PRO'),
('SBO_ANAGAMING','natalia.costa','Natalia Costa',false,true,'PRO'),
('SBO_ANAGAMING','natan.santiago','Natan Santiago',false,true,'PRO'),
('SBO_ANAGAMING','paola.teixeira','Paola Teixeira',true,false,NULL),
('SBO_ANAGAMING','pedro.souza','Pedro Souza',true,false,NULL),
('SBO_ANAGAMING','priscila.moutinho.axm','Priscila Moutinho AXM',true,false,NULL),
('SBO_ANAGAMING','rafael.conson','Rafael Conson',true,false,NULL),
('SBO_ANAGAMING','rafael.leite','Rafael Leite',false,false,NULL),
('SBO_ANAGAMING','rafale.conson','Rafael Conson',true,false,NULL),
('SBO_ANAGAMING','roberta.barbosa','Roberta Barbosa',true,false,NULL),
('SBO_ANAGAMING','roberto.giuliani','Roberto Giuliani',true,false,NULL),
('SBO_ANAGAMING','ronaldo.silva','Ronaldo Silva',false,true,'PRO'),
('SBO_ANAGAMING','samara.souza','Samara Souza',false,true,'PRO'),
('SBO_ANAGAMING','suporte','suporte FGR',false,false,NULL),
('SBO_ANAGAMING','suporte2','Suporte2',false,false,NULL),
('SBO_ANAGAMING','tagiane.gomide','Tagiane Gomide',false,true,'PRO'),
('SBO_ANAGAMING','talita.lacerda','Talita Lacerda',false,true,'PRO'),
('SBO_ANAGAMING','tamara.barboza','Tamara Barboza',false,true,'PRO'),
('SBO_ANAGAMING','tarcisio.ferreira','Tarcisio Ferreira',false,true,'PRO'),
('SBO_ANAGAMING','tatieli.murta','Tatieli Murta',false,true,'PRO'),
('SBO_ANAGAMING','teste','Teste',false,false,NULL),
('SBO_ANAGAMING','thadeu.botelho','Thadeu Botelho',false,true,'PRO'),
('SBO_ANAGAMING','thalitta.corona','Thaliatta Corona',false,false,NULL),
('SBO_ANAGAMING','thiago.andrade','Thiago Andrade',false,true,'PRO'),
('SBO_ANAGAMING','thiago.moreira','Thiago Moreira',false,true,'PRO'),
('SBO_ANAGAMING','thiago.sousa','Thiago Sousa',false,false,NULL),
('SBO_ANAGAMING','tiago.hubner','Tiago Hubner',true,false,NULL),
('SBO_ANAGAMING','valdineia.almeida','Valdineia Almeida',false,true,'PRO'),
('SBO_ANAGAMING','vicente.neto','Vicente Neto',false,true,'PRO'),
('SBO_ANAGAMING','victor.mello','Victor Mello',true,false,NULL),
('SBO_ANAGAMING','vinicius.ribeiro','Vinicius Ribeiro',false,true,'PRO'),
('SBO_ANAGAMING','vitor.fernandes','Vitor Fernandes',false,true,'PRO'),
('SBO_ANAGAMING','vitoria.evelyn','Vitoria Evelyn Silva',false,true,'PRO'),
('SBO_ANAGAMING','wellington.vieira','Wellingthon Vieira',false,true,'PRO'),
('SBO_CACTUS','AlertSvc','AlertSvc',false,false,NULL),
('SBO_CACTUS','Apiuser','Apiuser',false,false,NULL),
('SBO_CACTUS','Ludmila.braga','Ludmila Braga',true,false,NULL),
('SBO_CACTUS','PagCorp','PagCorp',false,false,NULL),
('SBO_CACTUS','Support','Support',false,false,NULL),
('SBO_CACTUS','alef.alves','Alef Alves',true,false,NULL),
('SBO_CACTUS','ana.fernandes','Ana Fernandes',true,true,'PRO'),
('SBO_CACTUS','anderson.araujo','Anderson Araujo',false,true,'PRO'),
('SBO_CACTUS','andre.andrade','Andre Andrade',false,true,'PRO'),
('SBO_CACTUS','andre.souza','Andre Souza',false,true,'PRO'),
('SBO_CACTUS','andre.viana','Andre Viana',true,false,NULL),
('SBO_CACTUS','antonio.guerardi','Antonio Guerardi',false,false,NULL),
('SBO_CACTUS','artur.angelo','Artur Angelo',false,true,'PRO'),
('SBO_CACTUS','augusto.nascimento','Augusto Nascimento',false,true,'PRO'),
('SBO_CACTUS','barbara.maciel','Barbara Maciel',false,true,'PRO'),
('SBO_CACTUS','blenda.pinheiro.ext','Blenda Pinheiro',false,true,'PRO'),
('SBO_CACTUS','bruno.diego','Bruno Diego',false,false,NULL),
('SBO_CACTUS','bruno.lima','Bruno Lima',false,true,'PRO'),
('SBO_CACTUS','camila.alcantara','Camila Alcantara',false,true,'PRO'),
('SBO_CACTUS','cesar.silva','Cesar Silva',false,true,'PRO'),
('SBO_CACTUS','cibele.costa','Cibele Costa',true,false,NULL),
('SBO_CACTUS','daniela.camargos','Daniela Camargos',false,true,'PRO'),
('SBO_CACTUS','diogo.faria','Diogo Faria',false,true,'PRO'),
('SBO_CACTUS','douglas.ferreira','Douglas Ferreira',false,true,'PRO'),
('SBO_CACTUS','douglas.silva','Douglas Silva',false,false,NULL),
('SBO_CACTUS','douglas.vinicius','Douglas Vinicius',false,false,NULL),
('SBO_CACTUS','eduardo.kiefer','Eduardo Kiefer',false,true,'PRO'),
('SBO_CACTUS','elisia.oliveira','Elisia Oliveira',false,false,NULL),
('SBO_CACTUS','felipe.coelho','Felipe Coelho',false,true,'PRO'),
('SBO_CACTUS','felipe.escudeiro','Felipe Escudeiro',false,true,'PRO'),
('SBO_CACTUS','fernanda.faria','Fernanda Faria',false,true,'PRO'),
('SBO_CACTUS','fernanda.lobato','Fernanda Lobato',false,true,'PRO'),
('SBO_CACTUS','fernando.honorato','Fernando Honorato',true,false,NULL),
('SBO_CACTUS','flavia.alves','Flavia Alves',false,true,'PRO'),
('SBO_CACTUS','gabriel.barbosa','Gabriel Barbosa',false,false,NULL),
('SBO_CACTUS','gabriela.moura','Gabriela Moura',false,true,'PRO'),
('SBO_CACTUS','graciela.fernandes','Graciela Fernandes',false,true,'PRO'),
('SBO_CACTUS','gustavo.coelho','Gustavo Coelho',false,true,'PRO'),
('SBO_CACTUS','gustavo.freitas','Gustavo Freitas',false,true,'PRO'),
('SBO_CACTUS','hugo.batista','Hugo Batista',false,false,NULL),
('SBO_CACTUS','isabelle.santos','Isabelle Santos',false,true,'PRO'),
('SBO_CACTUS','izabella.cristina','Izabella Cristina',false,true,'PRO'),
('SBO_CACTUS','janaina.bezerra','Janaina Bezerra',false,false,NULL),
('SBO_CACTUS','jean.gomes','Jean Gomes',false,true,'PRO'),
('SBO_CACTUS','jose.victor','Jose Victor',false,true,'PRO'),
('SBO_CACTUS','juliana.gavineli','Juliana Gavineli',false,true,'PRO'),
('SBO_CACTUS','juliana.monteiro','Juliana Monteiro',false,true,'PRO'),
('SBO_CACTUS','juliana.pinto','Juliana Pinto',false,false,NULL),
('SBO_CACTUS','juliana.rosa','Juliana Bernardin Rosa',false,true,'PRO'),
('SBO_CACTUS','ketlhenn.monteiro','Ketlhenn Monteiro',false,true,'PRO'),
('SBO_CACTUS','larissa.manzalli','Larissa Manzalli',false,true,'PRO'),
('SBO_CACTUS','laryssa.mendes','Laryssa Mendes',false,true,'PRO'),
('SBO_CACTUS','leonardo.clemente','Leonardo Clemente',false,true,'PRO'),
('SBO_CACTUS','leonardo.oliveira','Leonardo Oliveira',false,true,'PRO'),
('SBO_CACTUS','leonardo.ramos','Leonardo Ramos',false,true,'PRO'),
('SBO_CACTUS','lincoln.vaz','Lincoln Vaz',false,true,'PRO'),
('SBO_CACTUS','lucas.brandao','Lucas Brandao',false,true,'PRO'),
('SBO_CACTUS','lucas.carvalho','Lucas Carvalho',false,true,'PRO'),
('SBO_CACTUS','lucas.ferraz','Lucas Ferraz',false,true,'PRO'),
('SBO_CACTUS','lucas.silva','Lucas Silva',false,true,'PRO'),
('SBO_CACTUS','luciana.marques','Luciana Marques',false,false,NULL),
('SBO_CACTUS','luiza.duarte','Luiza Duarte',false,true,'PRO'),
('SBO_CACTUS','manager','Manager FGR Consultoria',false,true,'PRO'),
('SBO_CACTUS','marco.ferreira','Marco Ferreira',false,true,'PRO'),
('SBO_CACTUS','marco.tulio','Marco Tulio',false,true,'PRO'),
('SBO_CACTUS','marlon.pereira','Marlon Pereira',false,false,NULL),
('SBO_CACTUS','matheus.moreira','Matheus Moreira',false,true,'PRO'),
('SBO_CACTUS','matheus.viana','Matheus Viana',false,true,'PRO'),
('SBO_CACTUS','mauricio.farias','Mauricio Farias',false,true,'PRO'),
('SBO_CACTUS','miguel.valadares','Miguel Valadares',false,true,'PRO'),
('SBO_CACTUS','natalia.costa','Natalia Costa',false,true,'PRO'),
('SBO_CACTUS','natan.santiago','Natan Santiago',false,true,'PRO'),
('SBO_CACTUS','ricardo.lima','Ricardo Lima',false,false,NULL),
('SBO_CACTUS','roberto.giuliani','Roberto Giuliani',false,false,NULL),
('SBO_CACTUS','robson.luiz','Robson Luiz',false,false,NULL),
('SBO_CACTUS','ronaldo.silva','Ronaldo Silva',false,true,'PRO'),
('SBO_CACTUS','samara.medeiros','Samara Medeiros',false,false,NULL),
('SBO_CACTUS','samara.souza','Samara Souza',false,true,'PRO'),
('SBO_CACTUS','suporte','suporte FGR',false,false,NULL),
('SBO_CACTUS','tagiane.gomide','Tagiane Gomide',false,true,'PRO'),
('SBO_CACTUS','talita.lacerda','Talita Lacerda',false,true,'PRO'),
('SBO_CACTUS','tamara.barboza','Tamara Barboza',false,true,'PRO'),
('SBO_CACTUS','tarcisio.ferreira','Tarcisio Ferreira',false,true,'PRO'),
('SBO_CACTUS','tatieli.murta','Tatieli Murta',false,true,'PRO'),
('SBO_CACTUS','thadeu.botelho','Thadeu Botelho',false,true,'PRO'),
('SBO_CACTUS','thalitta.corona','Thaliatta Corona',false,false,NULL),
('SBO_CACTUS','thiago.andrade','Thiago Andrade',false,true,'PRO'),
('SBO_CACTUS','thiago.garrides','Thiago Garrides Lima',false,true,'PRO'),
('SBO_CACTUS','thiago.moreira','Thiago Moreira',false,true,'PRO'),
('SBO_CACTUS','thiago.sousa','Thiago Sousa',false,false,NULL),
('SBO_CACTUS','tiago.hubner','Tiago Hubner',false,false,NULL),
('SBO_CACTUS','valdineia.almeida','Valdineia Almeida',false,true,'PRO'),
('SBO_CACTUS','victor.mello','Victor Mello',false,false,NULL),
('SBO_CACTUS','vinicius.ribeiro','Vinicius Ribeiro',false,true,'PRO'),
('SBO_CACTUS','vitor.fernandes','Vitor Fernandes',false,true,'PRO'),
('SBO_CACTUS','vitoria.evelyn','Vitoria Evelyn',false,true,'PRO'),
('SBO_CACTUS','wellington.vieira','Wellingthon Vieira',false,true,'PRO')
ON CONFLICT (company_db, user_code) DO UPDATE SET user_name=EXCLUDED.user_name, is_locked=EXCLUDED.is_locked, has_license=EXCLUDED.has_license;