// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { runtime } from '@/config/runtime';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

if (runtime.isStandaloneLocal) {
  const noopChannel = {
    on() { return noopChannel; },
    subscribe(callback?: (status: string) => void) {
      callback?.("SUBSCRIBED");
      return noopChannel;
    },
    unsubscribe() {
      return Promise.resolve("ok");
    },
  };

  (supabase as any).channel = () => noopChannel;
  (supabase as any).removeChannel = () => Promise.resolve("ok");
}
